export const REQUEST_EPISODE_PENDING="REQUEST_EPISODE_PENDING";
export const REQUEST_EPISODE_SUCCESS="REQUEST_EPISODE_SUCCESS";
export const REQUEST_EPISODE_FAILED="REQUEST_EPISODE_FAILED";

export const CHANGE_SEARCH_FIELD="CHANGE_SEARCH_FIELD";
