// FETCH EPISODE LIST ACTION TYPE
export const REQUEST_EPISODE_PENDING="REQUEST_EPISODE_PENDING";
export const REQUEST_EPISODE_SUCCESS="REQUEST_EPISODE_SUCCESS";
export const REQUEST_EPISODE_FAILED="REQUEST_EPISODE_FAILED";
// FETCH RANDOM EPISODE ACTION TYPE
export const REQUEST_RAND_EPISODE_PENDING="REQUEST_RAND_EPISODE_PENDING";
export const REQUEST_RAND_EPISODE_SUCCESS="REQUEST_RAND_EPISODE_SUCCESS";
export const REQUEST_RAND_EPISODE_FAILED="REQUEST_RAND_EPISODE_FAILED";
// SEARCH PARAMS ACTION TYPE
export const SET_OFFSET="SET_OFFSET";
export const CHANGE_SEARCH_FIELD="CHANGE_SEARCH_FIELD";
// MEDIA PLAYER ACTION TYPE
export const SHOW_PLAYER="SHOW_PLAYER";
export const PLAY_CURRENT_EPISODE = "PLAY_CURRENT_EPISODE";
// SHOW + CLOSE SCORE MODAL ACTION TYPE
export const UPDATE_SCORE = "UPDATE_SCORE";
export const CLOSE_SCORE = "CLOSE_SCORE";
// USER + REGISTER ACTION TYPE
export const USER_SIGN_IN = "USER_SIGN_IN";
export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_SIGN_PENDING = "USER_SIGN_PENDING";
export const USER_SIGN_FAILED = "USER_SIGN_FAILED";

// USER FORM INPUT
export const CHANGE_USERNAME_FIELD = 'CHANGE_USERNAME_FIELD'
export const CHANGE_PW_FIELD = 'CHANGE_PW_FIELD'